/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as AuthJobsJobIdRouteImport } from './routes/_auth/jobs.$jobId'
import { Route as AuthJobsNewRouteImport } from './routes/_auth/jobs.new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJobsJobIdRoute = AuthJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsNewRoute = AuthJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/t/$token': typeof TTokenRoute
  '/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/jobs/new': typeof AuthJobsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/t/$token': typeof TTokenRoute
  '/': typeof AuthIndexRoute
  '/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/jobs/new': typeof AuthJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/t/$token': typeof TTokenRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/_auth/jobs/new': typeof AuthJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/t/$token' | '/jobs/$jobId' | '/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/t/$token' | '/' | '/jobs/$jobId' | '/jobs/new'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/t/$token'
    | '/_auth/'
    | '/_auth/jobs/$jobId'
    | '/_auth/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TTokenRoute: typeof TTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/jobs/$jobId': {
      id: '/_auth/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthJobsJobIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/jobs/new': {
      id: '/_auth/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthJobsNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthJobsJobIdRoute: typeof AuthJobsJobIdRoute
  AuthJobsNewRoute: typeof AuthJobsNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthJobsJobIdRoute: AuthJobsJobIdRoute,
  AuthJobsNewRoute: AuthJobsNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
