/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthTemplatesRouteImport } from './routes/_auth/templates'
import { Route as AuthWhatsappRouteImport } from './routes/_auth/whatsapp'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as AuthJobsJobIdRouteImport } from './routes/_auth/jobs.$jobId'
import { Route as AuthJobsNewRouteImport } from './routes/_auth/jobs.new'
import { Route as AuthJobsNewPhotoRouteImport } from './routes/_auth/jobs.new-photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTemplatesRoute = AuthTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWhatsappRoute = AuthWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJobsJobIdRoute = AuthJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsNewRoute = AuthJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsNewPhotoRoute = AuthJobsNewPhotoRouteImport.update({
  id: '/jobs/new-photo',
  path: '/jobs/new-photo',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthCalendarRoute
  '/dashboard': typeof AuthDashboardRoute
  '/reports': typeof AuthReportsRoute
  '/templates': typeof AuthTemplatesRoute
  '/whatsapp': typeof AuthWhatsappRoute
  '/t/$token': typeof TTokenRoute
  '/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/jobs/new': typeof AuthJobsNewRoute
  '/jobs/new-photo': typeof AuthJobsNewPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthCalendarRoute
  '/dashboard': typeof AuthDashboardRoute
  '/reports': typeof AuthReportsRoute
  '/templates': typeof AuthTemplatesRoute
  '/whatsapp': typeof AuthWhatsappRoute
  '/t/$token': typeof TTokenRoute
  '/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/jobs/new': typeof AuthJobsNewRoute
  '/jobs/new-photo': typeof AuthJobsNewPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/templates': typeof AuthTemplatesRoute
  '/_auth/whatsapp': typeof AuthWhatsappRoute
  '/t/$token': typeof TTokenRoute
  '/_auth/jobs/$jobId': typeof AuthJobsJobIdRoute
  '/_auth/jobs/new': typeof AuthJobsNewRoute
  '/_auth/jobs/new-photo': typeof AuthJobsNewPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/reports'
    | '/templates'
    | '/whatsapp'
    | '/t/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/new-photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/reports'
    | '/templates'
    | '/whatsapp'
    | '/t/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/new-photo'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/calendar'
    | '/_auth/dashboard'
    | '/_auth/reports'
    | '/_auth/templates'
    | '/_auth/whatsapp'
    | '/t/$token'
    | '/_auth/jobs/$jobId'
    | '/_auth/jobs/new'
    | '/_auth/jobs/new-photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TTokenRoute: typeof TTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/templates': {
      id: '/_auth/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/whatsapp': {
      id: '/_auth/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthWhatsappRouteImport
      parentRoute: typeof AuthRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/jobs/$jobId': {
      id: '/_auth/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthJobsJobIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/jobs/new': {
      id: '/_auth/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthJobsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/jobs/new-photo': {
      id: '/_auth/jobs/new-photo'
      path: '/jobs/new-photo'
      fullPath: '/jobs/new-photo'
      preLoaderRoute: typeof AuthJobsNewPhotoRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthTemplatesRoute: typeof AuthTemplatesRoute
  AuthWhatsappRoute: typeof AuthWhatsappRoute
  AuthJobsJobIdRoute: typeof AuthJobsJobIdRoute
  AuthJobsNewRoute: typeof AuthJobsNewRoute
  AuthJobsNewPhotoRoute: typeof AuthJobsNewPhotoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCalendarRoute: AuthCalendarRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthTemplatesRoute: AuthTemplatesRoute,
  AuthWhatsappRoute: AuthWhatsappRoute,
  AuthJobsJobIdRoute: AuthJobsJobIdRoute,
  AuthJobsNewRoute: AuthJobsNewRoute,
  AuthJobsNewPhotoRoute: AuthJobsNewPhotoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
